version: '3'
services:

  mongo:
    image: mongo:4.2.2
    container_name: mongo
    # security_opt:
    #   - seccomp:unconfined
    privileged: true
    command:
      - "numactl"
      - "--interleave=all"
      - "mongod"
      - "--bind_ip=0.0.0.0"
    volumes:
       - ./data/mongo:/data/db
    ports:
       - 27017:27017

  grip:
    image: bmeg/grip:latest
    container_name: grip
    volumes:
        - ./configs/grip_mongo_config.yml:/config/grip_config.yml
    entrypoint: ["grip", "server", "--config", "/config/grip_config.yml"]
    ports:
      - 8201:8201
      - 8202:8202
    depends_on:
      - mongo
