version: '3'
services:

  # mongo:
  #   image: mongo:4.2.2
  #   container_name: mongo
  #   privileged: true
  #   command:
  #     - "numactl"
  #     - "--interleave=all"
  #     - "mongod"
  #     - "--bind_ip=0.0.0.0"
  #   volumes:
  #      - ./data/mongo:/data/db
  #   ports:
  #      - 27017:27017

  # grip:
  #   image: bmeg/grip:latest
  #   container_name: grip
  #   volumes:
  #       - ./configs/grip_mongo_config.yml:/config/grip_config.yml
  #   entrypoint: ["grip", "server", "--config", "/config/grip_config.yml"]
  #   ports:
  #     - 8201:8201
  #     - 8202:8202
  #   depends_on:
  #     - mongo

  # etl:
  #   build: graph-etl
  #   container_name: etl
  #   environment:
  #     GRIP_HOST: grip:8201
  #   volumes:
  #     - ./data/:/etl/data
  #   depends_on:
  #     - mongo

  shiny:
    build: shiny-server
    container_name: shiny
    environment:
      GRIP_HOST: grip:8201
      GDAN_TMP_GRAPH: gdan_tmp
    command: ["R", "-e", "shiny::runApp('/srv/shiny-server/GDAN-TMP', host = '0.0.0.0', port = 3838)"]
    volumes:
      - ./configs/shiny-server.conf:/etc/shiny-server/shiny-server.conf
      - ./webdash:/srv/shiny-server/GDAN-TMP:ro
      - ./data:/mnt/data:ro
    ports:
      - 3838:3838
